---
title: "Using Highcharter lbjdata themes"
output: rmarkdown::html_vignette
author: "Matt Worthington"
opengraph:
  twitter:
    card: summary
    creator: "@mrworthington"
vignette: >
  %\VignetteIndexEntry{themes_hc}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Theming chart made in highchart with lbjdata

This is a basic example which shows you how to use lbjdata's highcharter theme. First, load the packages:

```{r example,message=FALSE, warning=FALSE}
library(lbjdata)
library(tidyverse)
library(janitor)
library(highcharter)
```

Then, import some data:

```{r provider_chart, message=FALSE, warning=FALSE}
provider_types <- read_csv("https://genesis.soc.texas.gov/files/accessibility/vaccineprovideraccessibilitydata.csv") %>% 
  clean_names() %>% 
  group_by(type) %>% 
  summarise(tot_shipped = sum(total_shipped),
            tot_avail = sum(vaccines_available)) %>% 
  drop_na() %>% 
  arrange(desc(tot_shipped))
```

Then, draw a chart with highcharter and add the theme:

```{r provider_chart, message=FALSE, warning=FALSE}

provider_types %>% 
  hchart("column", hcaes(x=type, y = tot_shipped, colors=type),
         name = "Total Shipped: ") %>% 
  hc_title(text="Vaccine Supply, By Type of Provider") %>% 
  hc_subtitle(text="Source: Texas Department of State Health Services") %>% 
  hc_add_theme(hc_theme_lbj())
```
